In [4]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(arr)
type(arr)

[1 2 3 4 5 6]


numpy.ndarray

In [16]:
arr2=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
arr3=np.array([[[2,4,6],[7,9,1]],[[2,3,5],[8,1,3]]])
print(arr3)

[[[2 4 6]
  [7 9 1]]

 [[2 3 5]
  [8 1 3]]]


In [23]:
arr4 = np.array([1, 2, 3, 4], ndmin=4)

print(arr4)
print('number of dimensions :', arr4.ndim)

[[[[1 2 3 4]]]]
number of dimensions : 4


In [24]:
print(arr[2:3])

[3]


In [29]:
char=['a','b','c','d','e']
print(char[1:3])
print(char[1:-1])

['b', 'c']
['b', 'c', 'd']


In [28]:
a='motorbike'
print(a[-4:])

bike
